export const resources = {
  apartments: {
    roles: ['admin', 'staff'],
    endpoint: '/apartments',
    title: 'หอพัก',
    subtitle: 'จัดการข้อมูลหอพัก',
    icon: 'bi-building',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'ชื่อหอพัก' },
      { key: 'city', label: 'จังหวัด/เมือง' },
      { key: 'total_rooms', label: 'จำนวนห้อง' },
      { key: 'postal_code', label: 'รหัสไปรษณีย์' },
    ],
    fields: [
      { name: 'name', label: 'ชื่อหอพัก', required: true },
      { name: 'address', label: 'ที่อยู่', required: true },
      { name: 'city', label: 'เมือง', required: true },
      { name: 'postal_code', label: 'รหัสไปรษณีย์', required: true },
      { name: 'total_rooms', label: 'จำนวนห้อง', type: 'number', required: true },
      { name: 'description', label: 'รายละเอียด', type: 'textarea' },
    ],
  },
  rooms: {
    roles: ['admin', 'staff'],
    endpoint: '/rooms',
    title: 'ห้องพัก',
    subtitle: 'จัดการห้องในแต่ละหอพัก',
    icon: 'bi-door-open',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'apartment_name', label: 'หอพัก' },
      { key: 'room_number', label: 'เลขห้อง' },
      { key: 'room_type', label: 'ประเภท' },
      { key: 'rent_price', label: 'ค่าเช่า', format: 'currency' },
      { key: 'status', label: 'สถานะ' },
    ],
    fields: [
      {
        name: 'apartment_id',
        label: 'หอพัก',
        type: 'select',
        required: true,
        optionsFrom: '/apartments',
        optionLabel: 'name',
      },
      { name: 'room_number', label: 'เลขห้อง', required: true },
      { name: 'room_type', label: 'ประเภทห้อง', required: true },
      { name: 'capacity', label: 'ความจุ', type: 'number', required: true },
      { name: 'rent_price', label: 'ค่าเช่า (บาท)', type: 'number', required: true },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'available', label: 'ว่าง' },
          { value: 'occupied', label: 'มีผู้เช่า' },
        ],
      },
    ],
  },
  tenants: {
    roles: ['admin', 'staff'],
    endpoint: '/tenants',
    title: 'ผู้เช่า',
    subtitle: 'ข้อมูลผู้เช่าและสัญญา',
    icon: 'bi-people',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'ชื่อ' },
      { key: 'room_number', label: 'ห้อง' },
      { key: 'phone', label: 'โทรศัพท์' },
      { key: 'status', label: 'สถานะ' },
    ],
    fields: [
      {
        name: 'room_id',
        label: 'ห้อง',
        type: 'select',
        required: true,
        optionsFrom: '/rooms',
        optionLabel: (r) => `${r.room_number} (${r.apartment_name || r.apartment_id})`,
      },
      { name: 'name', label: 'ชื่อ-นามสกุล', required: true },
      { name: 'phone', label: 'โทรศัพท์' },
      { name: 'email', label: 'อีเมล', type: 'email' },
      { name: 'id_card', label: 'เลขบัตรประชาชน' },
      { name: 'contract_start', label: 'เริ่มสัญญา', type: 'date', required: true },
      { name: 'contract_end', label: 'สิ้นสุดสัญญา', type: 'date' },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'active', label: 'ใช้งาน' },
          { value: 'inactive', label: 'ย้ายออก' },
        ],
      },
    ],
  },
  bills: {
    roles: ['admin', 'staff'],
    endpoint: '/bills',
    title: 'ใบแจ้งหนี้',
    subtitle: 'บิลค่าเช่าและค่าบริการ',
    icon: 'bi-receipt',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'tenant_name', label: 'ผู้เช่า' },
      { key: 'room_number', label: 'ห้อง' },
      { key: 'amount', label: 'ยอด', format: 'currency' },
      { key: 'due_date', label: 'ครบกำหนด', format: 'date' },
      { key: 'status', label: 'สถานะ' },
    ],
    fields: [
      {
        name: 'tenant_id',
        label: 'ผู้เช่า',
        type: 'select',
        required: true,
        optionsFrom: '/tenants',
        optionLabel: 'name',
      },
      { name: 'billing_date', label: 'วันที่ออกบิล', type: 'date', required: true },
      { name: 'due_date', label: 'วันครบกำหนด', type: 'date', required: true },
      { name: 'amount', label: 'ยอดรวม', type: 'number', required: true },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'pending', label: 'รอชำระ' },
          { value: 'paid', label: 'ชำระแล้ว' },
        ],
      },
      { name: 'payment_date', label: 'วันชำระ', type: 'date' },
    ],
  },
  maintenance: {
    roles: ['admin', 'staff'],
    endpoint: '/maintenance',
    title: 'แจ้งซ่อม',
    subtitle: 'รายการซ่อมบำรุง',
    icon: 'bi-tools',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'apartment_name', label: 'หอพัก' },
      { key: 'description', label: 'รายละเอียด' },
      { key: 'status', label: 'สถานะ' },
      { key: 'created_date', label: 'วันที่แจ้ง', format: 'datetime' },
    ],
    fields: [
      {
        name: 'apartment_id',
        label: 'หอพัก',
        type: 'select',
        required: true,
        optionsFrom: '/apartments',
        optionLabel: 'name',
      },
      { name: 'description', label: 'รายละเอียด', type: 'textarea', required: true },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'pending', label: 'รอดำเนินการ' },
          { value: 'in-progress', label: 'กำลังซ่อม' },
          { value: 'completed', label: 'เสร็จแล้ว' },
        ],
      },
      { name: 'completed_date', label: 'วันที่เสร็จ', type: 'datetime-local' },
    ],
  },
  utilities: {
    roles: ['admin', 'staff'],
    endpoint: '/utilities',
    title: 'สาธารณูปโภค',
    subtitle: 'ค่าน้ำ ไฟ อินเทอร์เน็ต',
    icon: 'bi-lightning',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'apartment_name', label: 'หอพัก' },
      { key: 'utility_name', label: 'รายการ' },
      { key: 'unit_price', label: 'ราคาต่อหน่วย', format: 'currency' },
    ],
    fields: [
      {
        name: 'apartment_id',
        label: 'หอพัก',
        type: 'select',
        required: true,
        optionsFrom: '/apartments',
        optionLabel: 'name',
      },
      { name: 'utility_name', label: 'ชื่อรายการ', required: true },
      { name: 'unit_price', label: 'ราคาต่อหน่วย', type: 'number', required: true },
    ],
  },
  contracts: {
    roles: ['admin', 'staff'],
    endpoint: '/contracts',
    title: 'สัญญาเช่า',
    subtitle: 'สัญญาระหว่างผู้เช่าและห้อง',
    icon: 'bi-file-earmark-text',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'tenant_name', label: 'ผู้เช่า' },
      { key: 'room_number', label: 'ห้อง' },
      { key: 'start_date', label: 'เริ่ม', format: 'date' },
      { key: 'status', label: 'สถานะ' },
    ],
    fields: [
      {
        name: 'tenant_id',
        label: 'ผู้เช่า',
        type: 'select',
        required: true,
        optionsFrom: '/tenants',
        optionLabel: 'name',
      },
      {
        name: 'room_id',
        label: 'ห้อง',
        type: 'select',
        required: true,
        optionsFrom: '/rooms',
        optionLabel: (r) => `${r.room_number} (${r.apartment_name || ''})`,
      },
      { name: 'start_date', label: 'วันเริ่มสัญญา', type: 'date', required: true },
      { name: 'end_date', label: 'วันสิ้นสุด', type: 'date' },
      { name: 'terms', label: 'เงื่อนไข', type: 'textarea' },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'active', label: 'ใช้งาน' },
          { value: 'expired', label: 'หมดอายุ' },
        ],
      },
    ],
  },
  'meter-readings': {
    roles: ['admin', 'staff'],
    endpoint: '/meter-readings',
    title: 'มิเตอร์',
    subtitle: 'บันทึกค่ามิเตอร์',
    icon: 'bi-speedometer',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'room_number', label: 'ห้อง' },
      { key: 'utility_name', label: 'ประเภท' },
      { key: 'reading_value', label: 'ค่าอ่าน' },
      { key: 'reading_date', label: 'วันที่', format: 'date' },
    ],
    fields: [
      {
        name: 'room_id',
        label: 'ห้อง',
        type: 'select',
        required: true,
        optionsFrom: '/rooms',
        optionLabel: (r) => `${r.room_number} (${r.apartment_name || ''})`,
      },
      {
        name: 'utility_id',
        label: 'สาธารณูปโภค',
        type: 'select',
        required: true,
        optionsFrom: '/utilities',
        optionLabel: 'utility_name',
      },
      { name: 'reading_value', label: 'ค่าอ่าน', type: 'number', required: true },
      { name: 'reading_date', label: 'วันที่อ่าน', type: 'date', required: true },
    ],
  },
  payments: {
    roles: ['admin', 'staff'],
    endpoint: '/payments',
    title: 'การชำระเงิน',
    subtitle: 'ประวัติการชำระ',
    icon: 'bi-cash-coin',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'tenant_name', label: 'ผู้เช่า' },
      { key: 'amount_paid', label: 'จำนวน', format: 'currency' },
      { key: 'payment_method', label: 'ช่องทาง' },
      { key: 'status', label: 'สถานะ' },
    ],
    fields: [
      {
        name: 'bill_id',
        label: 'ใบแจ้งหนี้',
        type: 'select',
        required: true,
        optionsFrom: '/bills',
        optionLabel: (b) => `#${b.id} - ${b.tenant_name || 'บิล'} (${b.amount})`,
      },
      { name: 'amount_paid', label: 'จำนวนที่ชำระ', type: 'number', required: true },
      { name: 'payment_method', label: 'ช่องทางชำระ' },
      {
        name: 'status',
        label: 'สถานะ',
        type: 'select',
        options: [
          { value: 'completed', label: 'สำเร็จ' },
          { value: 'pending', label: 'รอตรวจ' },
        ],
      },
    ],
  },
  'bill-items': {
    roles: ['admin', 'staff'],
    endpoint: '/bill-items',
    title: 'รายการบิล',
    subtitle: 'รายละเอียดในใบแจ้งหนี้',
    icon: 'bi-list-check',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'tenant_name', label: 'ผู้เช่า' },
      { key: 'description', label: 'รายการ' },
      { key: 'total', label: 'รวม', format: 'currency' },
    ],
    fields: [
      {
        name: 'bill_id',
        label: 'ใบแจ้งหนี้',
        type: 'select',
        required: true,
        optionsFrom: '/bills',
        optionLabel: (b) => `#${b.id} - ${b.tenant_name || ''}`,
      },
      { name: 'description', label: 'รายละเอียด', required: true },
      { name: 'quantity', label: 'จำนวน', type: 'number' },
      { name: 'unit_price', label: 'ราคาต่อหน่วย', type: 'number', required: true },
      { name: 'total', label: 'รวม', type: 'number', required: true },
    ],
  },
  users: {
    roles: ['admin'],
    endpoint: '/users',
    title: 'ผู้ใช้งาน',
    subtitle: 'จัดการบัญชี (เฉพาะ Admin)',
    icon: 'bi-person-gear',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'ชื่อ' },
      { key: 'email', label: 'อีเมล' },
      { key: 'role', label: 'บทบาท' },
    ],
    fields: [
      { name: 'name', label: 'ชื่อ', required: true },
      { name: 'email', label: 'อีเมล', type: 'email', required: true },
      { name: 'password', label: 'รหัสผ่าน', type: 'password', requiredOnCreate: true },
      {
        name: 'role',
        label: 'บทบาท',
        type: 'select',
        options: [
          { value: 'admin', label: 'Admin' },
          { value: 'staff', label: 'Staff (เจ้าหน้าที่)' },
          { value: 'tenant', label: 'Tenant (ผู้เช่า)' },
        ],
      },
    ],
  },
};
